// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: Login

#include "../ui.h"

// COMPONENT rfidContainer

lv_obj_t * ui_rfidContainer_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_rfidContainer;
    cui_rfidContainer = lv_obj_create(comp_parent);
    lv_obj_remove_style_all(cui_rfidContainer);
    lv_obj_set_width(cui_rfidContainer, 72);
    lv_obj_set_height(cui_rfidContainer, 39);
    lv_obj_set_x(cui_rfidContainer, -200);
    lv_obj_set_y(cui_rfidContainer, 107);
    lv_obj_set_align(cui_rfidContainer, LV_ALIGN_CENTER);
    lv_obj_clear_flag(cui_rfidContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t * cui_Label7;
    cui_Label7 = lv_label_create(cui_rfidContainer);
    lv_obj_set_width(cui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(cui_Label7, LV_ALIGN_LEFT_MID);
    lv_label_set_text(cui_Label7, "rfid:");

    lv_obj_t * cui_Label8;
    cui_Label8 = lv_label_create(cui_rfidContainer);
    lv_obj_set_width(cui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(cui_Label8, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(cui_Label8, "text");

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_RFIDCONTAINER_NUM);
    children[UI_COMP_RFIDCONTAINER_RFIDCONTAINER] = cui_rfidContainer;
    children[UI_COMP_RFIDCONTAINER_LABEL7] = cui_Label7;
    children[UI_COMP_RFIDCONTAINER_LABEL8] = cui_Label8;
    lv_obj_add_event_cb(cui_rfidContainer, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_rfidContainer, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_rfidContainer_create_hook(cui_rfidContainer);
    return cui_rfidContainer;
}

