// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: Login

#ifndef _UI_COMP_RFIDCONTAINER_H
#define _UI_COMP_RFIDCONTAINER_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT rfidContainer
#define UI_COMP_RFIDCONTAINER_RFIDCONTAINER 0
#define UI_COMP_RFIDCONTAINER_LABEL7 1
#define UI_COMP_RFIDCONTAINER_LABEL8 2
#define _UI_COMP_RFIDCONTAINER_NUM 3
lv_obj_t * ui_rfidContainer_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
