// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: Login

#ifndef UI_LOGIN_SCREEN_H
#define UI_LOGIN_SCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Login_Screen
extern void ui_Login_Screen_screen_init(void);
extern void ui_Login_Screen_screen_destroy(void);
extern lv_obj_t * ui_Login_Screen;
extern void ui_event_BackGround(lv_event_t * e);
extern lv_obj_t * ui_BackGround;
extern lv_obj_t * ui_Login_Container;
extern lv_obj_t * ui_User_Container;
extern void ui_event_UserNameText(lv_event_t * e);
extern lv_obj_t * ui_UserNameText;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Passwd_Container;
extern void ui_event_PassWordText(lv_event_t * e);
extern lv_obj_t * ui_PassWordText;
extern lv_obj_t * ui_Label1;
extern void ui_event_Button1(lv_event_t * e);
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Keyboard1;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

