// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: Login

#include "../ui.h"

lv_obj_t * ui_Login_Screen = NULL;
lv_obj_t * ui_BackGround = NULL;
lv_obj_t * ui_Login_Container = NULL;
lv_obj_t * ui_User_Container = NULL;
lv_obj_t * ui_UserNameText = NULL;
lv_obj_t * ui_Label3 = NULL;
lv_obj_t * ui_Passwd_Container = NULL;
lv_obj_t * ui_PassWordText = NULL;
lv_obj_t * ui_Label1 = NULL;
lv_obj_t * ui_Button1 = NULL;
lv_obj_t * ui_Label2 = NULL;
lv_obj_t * ui_Keyboard1 = NULL;
// event funtions
void ui_event_BackGround(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_UserNameText(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_FOCUSED) {
        _ui_keyboard_set_target(ui_Keyboard1,  ui_UserNameText);
        _ui_flag_modify(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}

void ui_event_PassWordText(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_FOCUSED) {
        _ui_keyboard_set_target(ui_Keyboard1,  ui_PassWordText);
        _ui_flag_modify(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}

void ui_event_Button1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        EventCallBack_login(e);
    }
}

// build funtions

void ui_Login_Screen_screen_init(void)
{
    ui_Login_Screen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Login_Screen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BackGround = lv_obj_create(ui_Login_Screen);
    lv_obj_set_width(ui_BackGround, 800);
    lv_obj_set_height(ui_BackGround, 480);
    lv_obj_set_x(ui_BackGround, 1);
    lv_obj_set_y(ui_BackGround, 1);
    lv_obj_set_align(ui_BackGround, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_BackGround, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Login_Container = lv_obj_create(ui_Login_Screen);
    lv_obj_remove_style_all(ui_Login_Container);
    lv_obj_set_width(ui_Login_Container, 270);
    lv_obj_set_height(ui_Login_Container, 170);
    lv_obj_set_align(ui_Login_Container, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Login_Container, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Login_Container, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Login_Container, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_User_Container = lv_obj_create(ui_Login_Container);
    lv_obj_remove_style_all(ui_User_Container);
    lv_obj_set_width(ui_User_Container, 270);
    lv_obj_set_height(ui_User_Container, 50);
    lv_obj_set_x(ui_User_Container, 0);
    lv_obj_set_y(ui_User_Container, -57);
    lv_obj_set_align(ui_User_Container, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_User_Container, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_UserNameText = lv_textarea_create(ui_User_Container);
    lv_obj_set_width(ui_UserNameText, 150);
    lv_obj_set_height(ui_UserNameText, 44);
    lv_obj_set_align(ui_UserNameText, LV_ALIGN_RIGHT_MID);
    lv_textarea_set_placeholder_text(ui_UserNameText, "请输入用户名...");
    lv_obj_set_style_text_font(ui_UserNameText, &ui_font_MiSans15, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label3 = lv_label_create(ui_User_Container);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, 10);
    lv_obj_set_y(ui_Label3, 0);
    lv_obj_set_align(ui_Label3, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label3, "用户名:");
    lv_obj_set_style_text_font(ui_Label3, &ui_font_MiSans18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Passwd_Container = lv_obj_create(ui_Login_Container);
    lv_obj_remove_style_all(ui_Passwd_Container);
    lv_obj_set_width(ui_Passwd_Container, 270);
    lv_obj_set_height(ui_Passwd_Container, 50);
    lv_obj_set_align(ui_Passwd_Container, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_Passwd_Container, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PassWordText = lv_textarea_create(ui_Passwd_Container);
    lv_obj_set_width(ui_PassWordText, 150);
    lv_obj_set_height(ui_PassWordText, 44);
    lv_obj_set_align(ui_PassWordText, LV_ALIGN_RIGHT_MID);
    lv_textarea_set_placeholder_text(ui_PassWordText, "请输入密码...");
    lv_obj_set_style_text_font(ui_PassWordText, &ui_font_MiSans15, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label1 = lv_label_create(ui_Passwd_Container);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, 10);
    lv_obj_set_y(ui_Label1, 0);
    lv_obj_set_align(ui_Label1, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label1, "密  码:");
    lv_obj_set_style_text_font(ui_Label1, &ui_font_MiSans18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button1 = lv_btn_create(ui_Login_Container);
    lv_obj_set_width(ui_Button1, 265);
    lv_obj_set_height(ui_Button1, 44);
    lv_obj_set_align(ui_Button1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label2 = lv_label_create(ui_Button1);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "登录");
    lv_obj_set_style_text_font(ui_Label2, &ui_font_MiSans15, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Keyboard1 = lv_keyboard_create(ui_Login_Screen);
    lv_obj_set_width(ui_Keyboard1, 418);
    lv_obj_set_height(ui_Keyboard1, 172);
    lv_obj_set_x(ui_Keyboard1, 2);
    lv_obj_set_y(ui_Keyboard1, 147);
    lv_obj_set_align(ui_Keyboard1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN);     /// Flags

    lv_obj_add_event_cb(ui_BackGround, ui_event_BackGround, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_UserNameText, ui_event_UserNameText, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PassWordText, ui_event_PassWordText, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button1, ui_event_Button1, LV_EVENT_ALL, NULL);
    lv_keyboard_set_textarea(ui_Keyboard1, ui_UserNameText);

}

void ui_Login_Screen_screen_destroy(void)
{
    if(ui_Login_Screen) lv_obj_del(ui_Login_Screen);

    // NULL screen variables
    ui_Login_Screen = NULL;
    ui_BackGround = NULL;
    ui_Login_Container = NULL;
    ui_User_Container = NULL;
    ui_UserNameText = NULL;
    ui_Label3 = NULL;
    ui_Passwd_Container = NULL;
    ui_PassWordText = NULL;
    ui_Label1 = NULL;
    ui_Button1 = NULL;
    ui_Label2 = NULL;
    ui_Keyboard1 = NULL;

}
