// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: Login

#ifndef UI_MAIN_SCREEN_H
#define UI_MAIN_SCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Main_Screen
extern void ui_Main_Screen_screen_init(void);
extern void ui_Main_Screen_screen_destroy(void);
extern lv_obj_t * ui_Main_Screen;
extern lv_obj_t * ui_Container4;
extern lv_obj_t * ui_Colorwheel1;
extern lv_obj_t * ui_Label5;
extern void ui_event_Button3(lv_event_t * e);
extern lv_obj_t * ui_Button3;
extern lv_obj_t * ui_Label4;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

