// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: Login

#include "../ui.h"

lv_obj_t * ui_Main_Screen = NULL;
lv_obj_t * ui_Container4 = NULL;
lv_obj_t * ui_Colorwheel1 = NULL;
lv_obj_t * ui_Label5 = NULL;
lv_obj_t * ui_Button3 = NULL;
lv_obj_t * ui_Label4 = NULL;
// event funtions
void ui_event_Button3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Login_Screen, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 300, 0, &ui_Login_Screen_screen_init);
    }
}

// build funtions

void ui_Main_Screen_screen_init(void)
{
    ui_Main_Screen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Main_Screen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container4 = lv_obj_create(ui_Main_Screen);
    lv_obj_remove_style_all(ui_Container4);
    lv_obj_set_width(ui_Container4, 300);
    lv_obj_set_height(ui_Container4, 300);
    lv_obj_set_align(ui_Container4, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container4, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Container4, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_SPACE_BETWEEN);
    lv_obj_clear_flag(ui_Container4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Colorwheel1 = lv_colorwheel_create(ui_Container4, true);
    lv_obj_set_width(ui_Colorwheel1, 150);
    lv_obj_set_height(ui_Colorwheel1, 150);
    lv_obj_set_x(ui_Colorwheel1, -83);
    lv_obj_set_y(ui_Colorwheel1, -17);
    lv_obj_set_align(ui_Colorwheel1, LV_ALIGN_CENTER);

    ui_Label5 = lv_label_create(ui_Colorwheel1);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "red");
    lv_obj_set_style_text_font(ui_Label5, &ui_font_MiSans15, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button3 = lv_btn_create(ui_Container4);
    lv_obj_set_width(ui_Button3, 100);
    lv_obj_set_height(ui_Button3, 50);
    lv_obj_set_x(ui_Button3, -32);
    lv_obj_set_y(ui_Button3, 100);
    lv_obj_set_align(ui_Button3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label4 = lv_label_create(ui_Button3);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "返回");
    lv_obj_set_style_text_font(ui_Label4, &ui_font_MiSans15, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Button3, ui_event_Button3, LV_EVENT_ALL, NULL);

}

void ui_Main_Screen_screen_destroy(void)
{
    if(ui_Main_Screen) lv_obj_del(ui_Main_Screen);

    // NULL screen variables
    ui_Main_Screen = NULL;
    ui_Container4 = NULL;
    ui_Colorwheel1 = NULL;
    ui_Label5 = NULL;
    ui_Button3 = NULL;
    ui_Label4 = NULL;

}
