// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "ui.h"

void led_change_fun(lv_event_t * e)
{
	// Your code here
}

void time_change_fun(lv_event_t * e)
{
	// Your code here
}

void bee_change_fun(lv_event_t * e)
{
	// Your code here
}

void btn_rfid(lv_event_t * e)
{
	// Your code here
}

void time_restart_fun(lv_event_t * e)
{
	// Your code here
}

void btn_v_start(lv_event_t * e)
{
	// Your code here
}

void btn_v_fastF(lv_event_t * e)
{
	// Your code here
}

void fun_call_slider(lv_event_t * e)
{
	// Your code here
}

void btn_v_lowF(lv_event_t * e)
{
	// Your code here
}
