// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void led_change_fun(lv_event_t * e);
void time_change_fun(lv_event_t * e);
void bee_change_fun(lv_event_t * e);
void btn_rfid(lv_event_t * e);
void time_restart_fun(lv_event_t * e);
void btn_v_start(lv_event_t * e);
void btn_v_fastF(lv_event_t * e);
void fun_call_slider(lv_event_t * e);
void btn_v_lowF(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
