// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: Login

#include "ui.h"

void EventCallBack_login(lv_event_t* e) {
  // 获取用户名和密码
  const char* username = lv_textarea_get_text(ui_UserNameText);
  const char* password = lv_textarea_get_text(ui_PassWordText);

  if (strcmp(username, "admin") == 0 && strcmp(password, "123456") == 0) {
    _ui_screen_change(&ui_Main_Screen, LV_SCR_LOAD_ANIM_MOVE_LEFT, 300, 0,
                      &ui_Main_Screen_screen_init);
    // 清空输入框
    // lv_textarea_set_text(ui_UserNameText, "");
    // lv_textarea_set_text(ui_PassWordText, "");
  }
  else {
    // 弹窗提示
    lv_obj_t* alert = lv_msgbox_create(NULL, "提示", "用户名或密码错误", NULL, true);
    lv_obj_set_style_text_font(alert, &ui_font_MiSans15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_center(alert);
  }
}